export enum TransactionType {
  "INVOICE" = "INVOICE",
  "EXPENSE" = "EXPENSE",
  "CUSTOMERPREPAYMENT" = "CUSTOMERPREPAYMENT",
  "ARPAYMENT" = "ARPAYMENT",
  "APPAYMENT" = "APPAYMENT",
  "TRANSFER" = "TRANSFER",
  "TRANSACTION" = "TRANSACTION",
  "SALE" = "SALE",
}
