export const VACATION_BONUS_PERCENTAGE = 0.25;
export const SUNDAY_BONUS_PERCENTAGE = 0.25;
export const MAX_WORK_WEEK_LIMIT = 48;
export const MAX_DOUBLE_PLAY_WORK_WEEK_LIMIT = 57;
export const JUSTIFIED_ABSENCES_PERCENTAGE = 0.6;
export const HOLIDAY_OR_REST_EXTRA_PAY_PERCENTAGE = 2;
export const DAILY_MEAL_COMPENSATION = 50;
