export const mainRoutes = {
  auth: "/api/auth",
  collaborators: "/api/collaborators",
  cleanUps: "/api/cleanUps",
  rfc: "/api/rfc",
  collaboratorLog: "/api/collaboratorLog",
  userLog: "/api/userLog",
  misc: "/api/misc",
  documentation: "/api/documentation",
  fcm: "/api/fcm",
  userClient: "/api/userClient",
  users: "/api/users",
  timeOffRequests: "/api/time-off-requests",
  tasks: "/api/tasks",
  workLogs: "/api/work-logs",
  attendanceRecords: "/api/attendance-records",
  billing: "/api/billing",
  authActivities: "/api/auth-activities",
  notifications: "/api/notifications",
  products: "/api/products",
  suppliers: "/api/suppliers",
  controlledPrescriptions: "/api/controlled-prescriptions",
  activityRegisterTypes: "/api/activity-register-types",
  activityRegister: "/api/activity-register",
};
