const rawData = {
  collaborator: {
    _id: "61e9f83a11d080f125a93e95",
    id: "61e9f83a11d080f125a93e95",
    first_name: "José Luis",
    last_name: "López Pérez",
    gender: "Masculino",
    email: "luizlop93@hotmail.com",
    phoneNumber: undefined,
    phoneNumber2: undefined,
    address: {
      line1: undefined,
      line2: undefined,
      city: undefined,
      state: undefined,
      country: undefined,
      zip: undefined,
    },
    curp: "LOPL931009HCSPRS05",
    imssNumber: "62169374543",
    rfcCode: " LOPL9310092R8",
    emergencyContact: undefined,
    emergencyContactPhone: undefined,
    role: "Colaborador",
    imgUrl:
      "https://res.cloudinary.com/dwalcv9li/image/upload/v1643821431/hv3d7z6aolh6uwk0m5to.png",
    images: [
      {
        __parentArray: [Circular],
        __index: 0,
        $__parent: {
          $__: {
            activePaths: {
              paths: {
                jobId: "init",
                col_code: "init",
                registeredDate: "init",
                last_name: "init",
                first_name: "init",
                role: "init",
                isDisplayedWeb: "init",
                isActive: "init",
                _id: "init",
                col_numId: "init",
                gender: "init",
                accessCode: "init",
                isRegistered: "init",
                position: "init",
                __v: "init",
                imgUrl: "init",
                textPresentation: "init",
                lastLogin: "init",
                startDate: "init",
                email: "init",
                password: "init",
                coverShift: "init",
                updatedAt: "init",
                weeklyHours: "init",
                images: "init",
                updatedBy: "init",
                createdAt: "init",
                contractDate: "init",
                curp: "init",
                degree: "init",
                imssEnrollmentDate: "init",
                imssNumber: "init",
                rfcCode: "init",
                hasIMSS: "init",
              },
              states: {
                require: {},
                default: {},
                init: {
                  _id: true,
                  first_name: true,
                  last_name: true,
                  role: true,
                  col_code: true,
                  col_numId: true,
                  isActive: true,
                  gender: true,
                  accessCode: true,
                  isRegistered: true,
                  position: true,
                  isDisplayedWeb: true,
                  __v: true,
                  imgUrl: true,
                  textPresentation: true,
                  lastLogin: true,
                  registeredDate: true,
                  startDate: true,
                  email: true,
                  password: true,
                  coverShift: true,
                  updatedAt: true,
                  weeklyHours: true,
                  images: true,
                  jobId: true,
                  updatedBy: true,
                  createdAt: true,
                  contractDate: true,
                  curp: true,
                  degree: true,
                  imssEnrollmentDate: true,
                  imssNumber: true,
                  rfcCode: true,
                  hasIMSS: true,
                },
              },
            },
            skipId: true,
            getters: {
              address: {
                line1: undefined,
                line2: undefined,
                city: undefined,
                state: undefined,
                country: undefined,
                zip: undefined,
              },
            },
            nestedPath: "address",
          },
          $isNew: false,
          _doc: {
            address: {},
            _id: {},
            first_name: "José Luis",
            last_name: "López Pérez",
            role: "Colaborador",
            col_code: "JLP",
            col_numId: 33,
            isActive: true,
            gender: "Masculino",
            accessCode: "IAfizo",
            isRegistered: true,
            position: "Veterinario B",
            isDisplayedWeb: true,
            __v: 0,
            imgUrl:
              "https://res.cloudinary.com/dwalcv9li/image/upload/v1643821431/hv3d7z6aolh6uwk0m5to.png",
            textPresentation:
              "Hola, soy el médico veterinario José Luis cuento con 4 años de experiencia en el área clínica  de pequeñas especies, mi enfoque en la rama de medicina veterinaria es la medicina interna ,   me encanta el manejo del paciente hospitalizado así también los cuidados de terapia intensiva, elegí esta carrera porque me apasiona la medicina animal ya que es muy amplia y siempre esta en actualización, en HVP me siento muy contento de formar parte de este equipo, la comunicación y el compañerismo que tenemos es muy bueno y agradable, seguimos aprendiendo cada día más y por hoy me siento agradecido.",
            lastLogin: "2024-05-27T14:27:36.859Z",
            registeredDate: "2022-02-08T14:18:50.459Z",
            startDate: "2020-01-24T00:00:00.000Z",
            email: "luizlop93@hotmail.com",
            password:
              "$2a$10$wWxtarP9oAHqW87o8endIOBm.Miga1IeBY4kRG07YfjjQRa6xAyBu",
            coverShift: true,
            updatedAt: "2025-02-01T19:30:01.464Z",
            weeklyHours: 36,
            images: [Circular],
            jobId: {},
            updatedBy: {},
            createdAt: "2024-10-21T14:41:45.012Z",
            contractDate: "2020-01-23T23:00:00.000Z",
            curp: "LOPL931009HCSPRS05",
            degree: "Titulado",
            imssEnrollmentDate: "2020-01-23T23:00:00.000Z",
            imssNumber: "62169374543",
            rfcCode: " LOPL9310092R8",
            hasIMSS: true,
          },
        },
        $__: {
          activePaths: {
            paths: {
              _id: "init",
              publicId: "init",
              url: "init",
              thumbnailUrl: "init",
              isMain: "init",
            },
            states: {
              default: {},
              init: {
                publicId: true,
                url: true,
                thumbnailUrl: true,
                isMain: true,
                _id: true,
              },
            },
          },
        },
        _doc: {
          publicId: "hvp/collaborators/JLP-1",
          url: "https://res.cloudinary.com/dwalcv9li/image/upload/v1732045792/hvp/collaborators/JLP-1.jpg",
          thumbnailUrl:
            "https://res.cloudinary.com/dwalcv9li/image/upload/c_thumb,g_face,h_100,w_100/v1732045792/hvp/collaborators/JLP-1.jpg",
          isMain: false,
          _id: {},
        },
        $isNew: false,
      },
    ],
    accessCode: "IAfizo",
    isRegistered: true,
    password: "$2a$10$wWxtarP9oAHqW87o8endIOBm.Miga1IeBY4kRG07YfjjQRa6xAyBu",
    isDisplayedWeb: true,
    textPresentation:
      "Hola, soy el médico veterinario José Luis cuento con 4 años de experiencia en el área clínica  de pequeñas especies, mi enfoque en la rama de medicina veterinaria es la medicina interna ,   me encanta el manejo del paciente hospitalizado así también los cuidados de terapia intensiva, elegí esta carrera porque me apasiona la medicina animal ya que es muy amplia y siempre esta en actualización, en HVP me siento muy contento de formar parte de este equipo, la comunicación y el compañerismo que tenemos es muy bueno y agradable, seguimos aprendiendo cada día más y por hoy me siento agradecido.",
    registeredDate: "2022-02-08T14:18:50.459Z",
    lastLogin: "2024-05-27T14:27:36.859Z",
    vacationsTakenBefore2021: undefined,
    col_code: "JLP",
    col_numId: 33,
    isActive: true,
    startDate: "2020-01-24T00:00:00.000Z",
    endDate: undefined,
    position: "Veterinario B",
    coverShift: true,
    weeklyHours: 36,
    jobId: "670a61c88ff5ac02957e5208",
    contractDate: "2020-01-23T23:00:00.000Z",
    hasIMSS: true,
    imssEnrollmentDate: "2020-01-23T23:00:00.000Z",
    paymentType: undefined,
    additionalCompensation: undefined,
    degree: "Titulado",
    createdAt: "2024-10-21T14:41:45.012Z",
    createdBy: undefined,
    updatedAt: "2025-02-01T19:30:01.464Z",
    updatedBy: {},
    baseContributionSalary: 10,
    dailyAverageSalary: 10,
    accumulatedAnnualIncomeRaisePercent: 10,
    accumulatedAnnualCommissionRaisePercent: 10,
    aggregatedMonthlyIncome: 10,
    imssSalaryBase: 10,
    averageDailyIncome: 10,
  },
  employment: {
    paymentType: "SALARY",
    seniorityBonusPercentage: 0.125,
    commissionBonusPercentage: 0.5,
    fixedIncomeByPosition: 3746.25,
    additionalFixedIncome: 0,
    fixedIncome: 3746.25,
    minimumOrdinaryIncome: 7875,
    degreeBonus: 225,
    receptionBonus: 0,
    trainingSupport: 0,
    physicalActivitySupport: 0,
    contributionBaseSalary: 454.9,
    averageOrdinaryIncome: 6992,
    averageIntegratedIncome: 9808,
    averageCommissionIncome: 4647,
    extraCompensations: [],
    collaboratorId: "61e9f83a11d080f125a93e95",
    jobId: "670a61c88ff5ac02957e5208",
    employmentStartDate: "2025-01-01T19:30:16.000Z",
    isActive: true,
    weeklyHours: 36,
    createdBy: "61dff1cb4131595911ad13fb",
    updatedBy: "61dff1cb4131595911ad13fb",
    createdAt: "2025-02-01T19:55:32.741Z",
    updatedAt: "2025-02-02T00:35:20.229Z",
    id: "679e7c34790fa92000bd2a07",
    employmentEndDate: undefined,
  },
  job: {
    annualRaisePercent: 2.5,
    quarterlyCommissionRaisePercent: 2.5,
    paymentType: "SALARY",
    sortingOrder: 22,
    incomeMultiplier: 1,
    expectedCommissionsPercentage: 0.4,
    expectedMinimumIncome: 10500,
    expressBranchCompensation: 0,
    active: true,
    baseIncome: 4440,
    description: "",
    hourlyRate: 0,
    minimumIncome: 10500,
    title: "Veterinario B",
    createdAt: "2024-10-12T11:47:20.879Z",
    updatedAt: "2025-02-01T19:23:52.980Z",
    updatedBy: "61dff1cb4131595911ad13fb",
    id: "670a61c88ff5ac02957e5208",
    createdBy: undefined,
  },
  attendanceReport: {
    collaboratorId: "61e9f83a11d080f125a93e95",
    startDate: "2025-01-16T06:00:00.000Z",
    endDate: "2025-01-31T06:00:00.000Z",
    collaboratorDayReports: [
      {
        date: {
          $L: "en",
          $d: "2025-01-13T06:00:00.000Z",
          $y: 2025,
          $M: 0,
          $D: 13,
          $W: 1,
          $H: 0,
          $m: 0,
          $s: 0,
          $ms: 0,
          $x: {},
          $isDayjsObject: true,
        },
        shiftStart: {
          $L: "en",
          $d: "2025-01-13T14:00:00.000Z",
          $y: 2025,
          $M: 0,
          $D: 13,
          $W: 1,
          $H: 8,
          $m: 0,
          $s: 0,
          $ms: 0,
          $x: {
            $localOffset: 360,
            $timezone: "America/Mexico_City",
          },
          $isDayjsObject: true,
          $offset: -360,
        },
        shiftEnd: {
          $L: "en",
          $d: "2025-01-14T02:00:00.000Z",
          $y: 2025,
          $M: 0,
          $D: 13,
          $W: 1,
          $H: 20,
          $m: 0,
          $s: 0,
          $ms: 0,
          $x: {
            $localOffset: 360,
            $timezone: "America/Mexico_City",
          },
          $isDayjsObject: true,
          $offset: -360,
        },
        attendanceStart: {
          $L: "en",
          $d: "2025-01-13T14:06:59.097Z",
          $y: 2025,
          $M: 0,
          $D: 13,
          $W: 1,
          $H: 8,
          $m: 6,
          $s: 59,
          $ms: 97,
          $x: {},
          $isDayjsObject: true,
        },
        attendanceEnd: {
          $L: "en",
          $d: "2025-01-14T02:00:00.000Z",
          $y: 2025,
          $M: 0,
          $D: 13,
          $W: 1,
          $H: 20,
          $m: 0,
          $s: 0,
          $ms: 0,
          $x: {},
          $isDayjsObject: true,
        },
        workingDayType: "Jornada ordinaria",
        assignedHours: 12,
        workedHours: 11.883333333333333,
        extraHours: -0.11666666666666714,
        delayMinutes: 6,
        anticipatedMinutes: 0,
        timeOffRequestType: undefined,
        branch: "Harbor",
      },
      {
        date: {
          $L: "en",
          $d: "2025-01-14T06:00:00.000Z",
          $y: 2025,
          $M: 0,
          $D: 14,
          $W: 2,
          $H: 0,
          $m: 0,
          $s: 0,
          $ms: 0,
          $x: {},
          $isDayjsObject: true,
        },
        shiftStart: undefined,
        shiftEnd: undefined,
        attendanceStart: undefined,
        attendanceEnd: undefined,
        workingDayType: "Descanso",
        assignedHours: 0,
        workedHours: 0,
        extraHours: 0,
        delayMinutes: 0,
        anticipatedMinutes: 0,
        timeOffRequestType: undefined,
        branch: undefined,
      },
      {
        date: {
          $L: "en",
          $d: "2025-01-15T06:00:00.000Z",
          $y: 2025,
          $M: 0,
          $D: 15,
          $W: 3,
          $H: 0,
          $m: 0,
          $s: 0,
          $ms: 0,
          $x: {},
          $isDayjsObject: true,
        },
        shiftStart: undefined,
        shiftEnd: undefined,
        attendanceStart: undefined,
        attendanceEnd: undefined,
        workingDayType: "Descanso",
        assignedHours: 0,
        workedHours: 0,
        extraHours: 0,
        delayMinutes: 0,
        anticipatedMinutes: 0,
        timeOffRequestType: undefined,
        branch: undefined,
      },
      {
        date: {
          $L: "en",
          $d: "2025-01-16T06:00:00.000Z",
          $y: 2025,
          $M: 0,
          $D: 16,
          $W: 4,
          $H: 0,
          $m: 0,
          $s: 0,
          $ms: 0,
          $x: {},
          $isDayjsObject: true,
        },
        shiftStart: {
          $L: "en",
          $d: "2025-01-16T14:00:00.000Z",
          $y: 2025,
          $M: 0,
          $D: 16,
          $W: 4,
          $H: 8,
          $m: 0,
          $s: 0,
          $ms: 0,
          $x: {
            $localOffset: 360,
            $timezone: "America/Mexico_City",
          },
          $isDayjsObject: true,
          $offset: -360,
        },
        shiftEnd: {
          $L: "en",
          $d: "2025-01-17T02:00:00.000Z",
          $y: 2025,
          $M: 0,
          $D: 16,
          $W: 4,
          $H: 20,
          $m: 0,
          $s: 0,
          $ms: 0,
          $x: {
            $localOffset: 360,
            $timezone: "America/Mexico_City",
          },
          $isDayjsObject: true,
          $offset: -360,
        },
        attendanceStart: {
          $L: "en",
          $d: "2025-01-16T14:07:36.223Z",
          $y: 2025,
          $M: 0,
          $D: 16,
          $W: 4,
          $H: 8,
          $m: 7,
          $s: 36,
          $ms: 223,
          $x: {},
          $isDayjsObject: true,
        },
        attendanceEnd: {
          $L: "en",
          $d: "2025-01-17T02:00:00.000Z",
          $y: 2025,
          $M: 0,
          $D: 16,
          $W: 4,
          $H: 20,
          $m: 0,
          $s: 0,
          $ms: 0,
          $x: {},
          $isDayjsObject: true,
        },
        workingDayType: "Jornada ordinaria",
        assignedHours: 12,
        workedHours: 11.866666666666667,
        extraHours: -0.13333333333333286,
        delayMinutes: 7,
        anticipatedMinutes: 0,
        timeOffRequestType: undefined,
        branch: "Harbor",
      },
      {
        date: {
          $L: "en",
          $d: "2025-01-17T06:00:00.000Z",
          $y: 2025,
          $M: 0,
          $D: 17,
          $W: 5,
          $H: 0,
          $m: 0,
          $s: 0,
          $ms: 0,
          $x: {},
          $isDayjsObject: true,
        },
        shiftStart: {
          $L: "en",
          $d: "2025-01-17T14:00:00.000Z",
          $y: 2025,
          $M: 0,
          $D: 17,
          $W: 5,
          $H: 8,
          $m: 0,
          $s: 0,
          $ms: 0,
          $x: {
            $localOffset: 360,
            $timezone: "America/Mexico_City",
          },
          $isDayjsObject: true,
          $offset: -360,
        },
        shiftEnd: {
          $L: "en",
          $d: "2025-01-18T02:00:00.000Z",
          $y: 2025,
          $M: 0,
          $D: 17,
          $W: 5,
          $H: 20,
          $m: 0,
          $s: 0,
          $ms: 0,
          $x: {
            $localOffset: 360,
            $timezone: "America/Mexico_City",
          },
          $isDayjsObject: true,
          $offset: -360,
        },
        attendanceStart: {
          $L: "en",
          $d: "2025-01-17T14:06:22.689Z",
          $y: 2025,
          $M: 0,
          $D: 17,
          $W: 5,
          $H: 8,
          $m: 6,
          $s: 22,
          $ms: 689,
          $x: {},
          $isDayjsObject: true,
        },
        attendanceEnd: {
          $L: "en",
          $d: "2025-01-18T02:05:43.229Z",
          $y: 2025,
          $M: 0,
          $D: 17,
          $W: 5,
          $H: 20,
          $m: 5,
          $s: 43,
          $ms: 229,
          $x: {},
          $isDayjsObject: true,
        },
        workingDayType: "Jornada ordinaria",
        assignedHours: 12,
        workedHours: 11.983333333333333,
        extraHours: -0.016666666666667496,
        delayMinutes: 6,
        anticipatedMinutes: -5,
        timeOffRequestType: undefined,
        branch: "Harbor",
      },
      {
        date: {
          $L: "en",
          $d: "2025-01-18T06:00:00.000Z",
          $y: 2025,
          $M: 0,
          $D: 18,
          $W: 6,
          $H: 0,
          $m: 0,
          $s: 0,
          $ms: 0,
          $x: {},
          $isDayjsObject: true,
        },
        shiftStart: undefined,
        shiftEnd: undefined,
        attendanceStart: undefined,
        attendanceEnd: undefined,
        workingDayType: "Descanso",
        assignedHours: 0,
        workedHours: 0,
        extraHours: 0,
        delayMinutes: 0,
        anticipatedMinutes: 0,
        timeOffRequestType: undefined,
        branch: undefined,
      },
      {
        date: {
          $L: "en",
          $d: "2025-01-19T06:00:00.000Z",
          $y: 2025,
          $M: 0,
          $D: 19,
          $W: 0,
          $H: 0,
          $m: 0,
          $s: 0,
          $ms: 0,
          $x: {},
          $isDayjsObject: true,
        },
        shiftStart: {
          $L: "en",
          $d: "2025-01-19T14:00:00.000Z",
          $y: 2025,
          $M: 0,
          $D: 19,
          $W: 0,
          $H: 8,
          $m: 0,
          $s: 0,
          $ms: 0,
          $x: {
            $localOffset: 360,
            $timezone: "America/Mexico_City",
          },
          $isDayjsObject: true,
          $offset: -360,
        },
        shiftEnd: {
          $L: "en",
          $d: "2025-01-20T02:00:00.000Z",
          $y: 2025,
          $M: 0,
          $D: 19,
          $W: 0,
          $H: 20,
          $m: 0,
          $s: 0,
          $ms: 0,
          $x: {
            $localOffset: 360,
            $timezone: "America/Mexico_City",
          },
          $isDayjsObject: true,
          $offset: -360,
        },
        attendanceStart: {
          $L: "en",
          $d: "2025-01-19T14:05:50.654Z",
          $y: 2025,
          $M: 0,
          $D: 19,
          $W: 0,
          $H: 8,
          $m: 5,
          $s: 50,
          $ms: 654,
          $x: {},
          $isDayjsObject: true,
        },
        attendanceEnd: {
          $L: "en",
          $d: "2025-01-20T02:27:53.029Z",
          $y: 2025,
          $M: 0,
          $D: 19,
          $W: 0,
          $H: 20,
          $m: 27,
          $s: 53,
          $ms: 29,
          $x: {},
          $isDayjsObject: true,
        },
        workingDayType: "Jornada ordinaria",
        assignedHours: 12,
        workedHours: 12.366666666666667,
        extraHours: 0.36666666666666714,
        delayMinutes: 5,
        anticipatedMinutes: -27,
        timeOffRequestType: undefined,
        branch: "Urban",
      },
      {
        date: {
          $L: "en",
          $d: "2025-01-20T06:00:00.000Z",
          $y: 2025,
          $M: 0,
          $D: 20,
          $W: 1,
          $H: 0,
          $m: 0,
          $s: 0,
          $ms: 0,
          $x: {},
          $isDayjsObject: true,
        },
        shiftStart: {
          $L: "en",
          $d: "2025-01-20T14:00:00.000Z",
          $y: 2025,
          $M: 0,
          $D: 20,
          $W: 1,
          $H: 8,
          $m: 0,
          $s: 0,
          $ms: 0,
          $x: {
            $localOffset: 360,
            $timezone: "America/Mexico_City",
          },
          $isDayjsObject: true,
          $offset: -360,
        },
        shiftEnd: {
          $L: "en",
          $d: "2025-01-21T02:00:00.000Z",
          $y: 2025,
          $M: 0,
          $D: 20,
          $W: 1,
          $H: 20,
          $m: 0,
          $s: 0,
          $ms: 0,
          $x: {
            $localOffset: 360,
            $timezone: "America/Mexico_City",
          },
          $isDayjsObject: true,
          $offset: -360,
        },
        attendanceStart: {
          $L: "en",
          $d: "2025-01-20T14:10:41.117Z",
          $y: 2025,
          $M: 0,
          $D: 20,
          $W: 1,
          $H: 8,
          $m: 10,
          $s: 41,
          $ms: 117,
          $x: {},
          $isDayjsObject: true,
        },
        attendanceEnd: {
          $L: "en",
          $d: "2025-01-21T02:30:22.643Z",
          $y: 2025,
          $M: 0,
          $D: 20,
          $W: 1,
          $H: 20,
          $m: 30,
          $s: 22,
          $ms: 643,
          $x: {},
          $isDayjsObject: true,
        },
        workingDayType: "Jornada ordinaria",
        assignedHours: 12,
        workedHours: 12.316666666666666,
        extraHours: 0.31666666666666643,
        delayMinutes: 10,
        anticipatedMinutes: -30,
        timeOffRequestType: undefined,
        branch: "Urban",
      },
      {
        date: {
          $L: "en",
          $d: "2025-01-21T06:00:00.000Z",
          $y: 2025,
          $M: 0,
          $D: 21,
          $W: 2,
          $H: 0,
          $m: 0,
          $s: 0,
          $ms: 0,
          $x: {},
          $isDayjsObject: true,
        },
        shiftStart: {
          $L: "en",
          $d: "2025-01-21T14:00:00.000Z",
          $y: 2025,
          $M: 0,
          $D: 21,
          $W: 2,
          $H: 8,
          $m: 0,
          $s: 0,
          $ms: 0,
          $x: {
            $localOffset: 360,
            $timezone: "America/Mexico_City",
          },
          $isDayjsObject: true,
          $offset: -360,
        },
        shiftEnd: {
          $L: "en",
          $d: "2025-01-22T02:00:00.000Z",
          $y: 2025,
          $M: 0,
          $D: 21,
          $W: 2,
          $H: 20,
          $m: 0,
          $s: 0,
          $ms: 0,
          $x: {
            $localOffset: 360,
            $timezone: "America/Mexico_City",
          },
          $isDayjsObject: true,
          $offset: -360,
        },
        attendanceStart: {
          $L: "en",
          $d: "2025-01-21T14:12:24.749Z",
          $y: 2025,
          $M: 0,
          $D: 21,
          $W: 2,
          $H: 8,
          $m: 12,
          $s: 24,
          $ms: 749,
          $x: {},
          $isDayjsObject: true,
        },
        attendanceEnd: {
          $L: "en",
          $d: "2025-01-22T03:11:50.012Z",
          $y: 2025,
          $M: 0,
          $D: 21,
          $W: 2,
          $H: 21,
          $m: 11,
          $s: 50,
          $ms: 12,
          $x: {},
          $isDayjsObject: true,
        },
        workingDayType: "Retardo",
        assignedHours: 12,
        workedHours: 12.983333333333333,
        extraHours: 0.9833333333333325,
        delayMinutes: 12,
        anticipatedMinutes: -71,
        timeOffRequestType: undefined,
        branch: "Harbor",
      },
      {
        date: {
          $L: "en",
          $d: "2025-01-22T06:00:00.000Z",
          $y: 2025,
          $M: 0,
          $D: 22,
          $W: 3,
          $H: 0,
          $m: 0,
          $s: 0,
          $ms: 0,
          $x: {},
          $isDayjsObject: true,
        },
        shiftStart: {
          $L: "en",
          $d: "2025-01-22T14:00:00.000Z",
          $y: 2025,
          $M: 0,
          $D: 22,
          $W: 3,
          $H: 8,
          $m: 0,
          $s: 0,
          $ms: 0,
          $x: {
            $localOffset: 360,
            $timezone: "America/Mexico_City",
          },
          $isDayjsObject: true,
          $offset: -360,
        },
        shiftEnd: {
          $L: "en",
          $d: "2025-01-23T02:00:00.000Z",
          $y: 2025,
          $M: 0,
          $D: 22,
          $W: 3,
          $H: 20,
          $m: 0,
          $s: 0,
          $ms: 0,
          $x: {
            $localOffset: 360,
            $timezone: "America/Mexico_City",
          },
          $isDayjsObject: true,
          $offset: -360,
        },
        attendanceStart: {
          $L: "en",
          $d: "2025-01-22T14:10:40.726Z",
          $y: 2025,
          $M: 0,
          $D: 22,
          $W: 3,
          $H: 8,
          $m: 10,
          $s: 40,
          $ms: 726,
          $x: {},
          $isDayjsObject: true,
        },
        attendanceEnd: {
          $L: "en",
          $d: "2025-01-23T02:09:00.653Z",
          $y: 2025,
          $M: 0,
          $D: 22,
          $W: 3,
          $H: 20,
          $m: 9,
          $s: 0,
          $ms: 653,
          $x: {},
          $isDayjsObject: true,
        },
        workingDayType: "Jornada ordinaria",
        assignedHours: 12,
        workedHours: 11.966666666666667,
        extraHours: -0.033333333333333215,
        delayMinutes: 10,
        anticipatedMinutes: -9,
        timeOffRequestType: undefined,
        branch: "Harbor",
      },
      {
        date: {
          $L: "en",
          $d: "2025-01-23T06:00:00.000Z",
          $y: 2025,
          $M: 0,
          $D: 23,
          $W: 4,
          $H: 0,
          $m: 0,
          $s: 0,
          $ms: 0,
          $x: {},
          $isDayjsObject: true,
        },
        shiftStart: undefined,
        shiftEnd: undefined,
        attendanceStart: undefined,
        attendanceEnd: undefined,
        workingDayType: "Descanso",
        assignedHours: 0,
        workedHours: 0,
        extraHours: 0,
        delayMinutes: 0,
        anticipatedMinutes: 0,
        timeOffRequestType: undefined,
        branch: undefined,
      },
      {
        date: {
          $L: "en",
          $d: "2025-01-24T06:00:00.000Z",
          $y: 2025,
          $M: 0,
          $D: 24,
          $W: 5,
          $H: 0,
          $m: 0,
          $s: 0,
          $ms: 0,
          $x: {},
          $isDayjsObject: true,
        },
        shiftStart: undefined,
        shiftEnd: undefined,
        attendanceStart: undefined,
        attendanceEnd: undefined,
        workingDayType: "Descanso",
        assignedHours: 0,
        workedHours: 0,
        extraHours: 0,
        delayMinutes: 0,
        anticipatedMinutes: 0,
        timeOffRequestType: undefined,
        branch: undefined,
      },
      {
        date: {
          $L: "en",
          $d: "2025-01-25T06:00:00.000Z",
          $y: 2025,
          $M: 0,
          $D: 25,
          $W: 6,
          $H: 0,
          $m: 0,
          $s: 0,
          $ms: 0,
          $x: {},
          $isDayjsObject: true,
        },
        shiftStart: {
          $L: "en",
          $d: "2025-01-25T14:00:00.000Z",
          $y: 2025,
          $M: 0,
          $D: 25,
          $W: 6,
          $H: 8,
          $m: 0,
          $s: 0,
          $ms: 0,
          $x: {
            $localOffset: 360,
            $timezone: "America/Mexico_City",
          },
          $isDayjsObject: true,
          $offset: -360,
        },
        shiftEnd: {
          $L: "en",
          $d: "2025-01-26T02:00:00.000Z",
          $y: 2025,
          $M: 0,
          $D: 25,
          $W: 6,
          $H: 20,
          $m: 0,
          $s: 0,
          $ms: 0,
          $x: {
            $localOffset: 360,
            $timezone: "America/Mexico_City",
          },
          $isDayjsObject: true,
          $offset: -360,
        },
        attendanceStart: {
          $L: "en",
          $d: "2025-01-25T14:12:43.683Z",
          $y: 2025,
          $M: 0,
          $D: 25,
          $W: 6,
          $H: 8,
          $m: 12,
          $s: 43,
          $ms: 683,
          $x: {},
          $isDayjsObject: true,
        },
        attendanceEnd: {
          $L: "en",
          $d: "2025-01-26T02:16:45.243Z",
          $y: 2025,
          $M: 0,
          $D: 25,
          $W: 6,
          $H: 20,
          $m: 16,
          $s: 45,
          $ms: 243,
          $x: {},
          $isDayjsObject: true,
        },
        workingDayType: "Retardo",
        assignedHours: 12,
        workedHours: 12.066666666666666,
        extraHours: 0.06666666666666643,
        delayMinutes: 12,
        anticipatedMinutes: -16,
        timeOffRequestType: undefined,
        branch: "Harbor",
      },
      {
        date: {
          $L: "en",
          $d: "2025-01-26T06:00:00.000Z",
          $y: 2025,
          $M: 0,
          $D: 26,
          $W: 0,
          $H: 0,
          $m: 0,
          $s: 0,
          $ms: 0,
          $x: {},
          $isDayjsObject: true,
        },
        shiftStart: undefined,
        shiftEnd: undefined,
        attendanceStart: undefined,
        attendanceEnd: undefined,
        workingDayType: "Descanso",
        assignedHours: 0,
        workedHours: 0,
        extraHours: 0,
        delayMinutes: 0,
        anticipatedMinutes: 0,
        timeOffRequestType: undefined,
        branch: undefined,
      },
      {
        date: {
          $L: "en",
          $d: "2025-01-27T06:00:00.000Z",
          $y: 2025,
          $M: 0,
          $D: 27,
          $W: 1,
          $H: 0,
          $m: 0,
          $s: 0,
          $ms: 0,
          $x: {},
          $isDayjsObject: true,
        },
        shiftStart: {
          $L: "en",
          $d: "2025-01-27T14:00:00.000Z",
          $y: 2025,
          $M: 0,
          $D: 27,
          $W: 1,
          $H: 8,
          $m: 0,
          $s: 0,
          $ms: 0,
          $x: {
            $localOffset: 360,
            $timezone: "America/Mexico_City",
          },
          $isDayjsObject: true,
          $offset: -360,
        },
        shiftEnd: {
          $L: "en",
          $d: "2025-01-28T02:00:00.000Z",
          $y: 2025,
          $M: 0,
          $D: 27,
          $W: 1,
          $H: 20,
          $m: 0,
          $s: 0,
          $ms: 0,
          $x: {
            $localOffset: 360,
            $timezone: "America/Mexico_City",
          },
          $isDayjsObject: true,
          $offset: -360,
        },
        attendanceStart: {
          $L: "en",
          $d: "2025-01-27T14:10:50.738Z",
          $y: 2025,
          $M: 0,
          $D: 27,
          $W: 1,
          $H: 8,
          $m: 10,
          $s: 50,
          $ms: 738,
          $x: {},
          $isDayjsObject: true,
        },
        attendanceEnd: {
          $L: "en",
          $d: "2025-01-28T02:12:13.181Z",
          $y: 2025,
          $M: 0,
          $D: 27,
          $W: 1,
          $H: 20,
          $m: 12,
          $s: 13,
          $ms: 181,
          $x: {},
          $isDayjsObject: true,
        },
        workingDayType: "Jornada ordinaria",
        assignedHours: 12,
        workedHours: 12.016666666666667,
        extraHours: 0.016666666666667496,
        delayMinutes: 10,
        anticipatedMinutes: -12,
        timeOffRequestType: undefined,
        branch: "Harbor",
      },
      {
        date: {
          $L: "en",
          $d: "2025-01-28T06:00:00.000Z",
          $y: 2025,
          $M: 0,
          $D: 28,
          $W: 2,
          $H: 0,
          $m: 0,
          $s: 0,
          $ms: 0,
          $x: {},
          $isDayjsObject: true,
        },
        shiftStart: undefined,
        shiftEnd: undefined,
        attendanceStart: undefined,
        attendanceEnd: undefined,
        workingDayType: "Descanso",
        assignedHours: 0,
        workedHours: 0,
        extraHours: 0,
        delayMinutes: 0,
        anticipatedMinutes: 0,
        timeOffRequestType: undefined,
        branch: undefined,
      },
      {
        date: {
          $L: "en",
          $d: "2025-01-29T06:00:00.000Z",
          $y: 2025,
          $M: 0,
          $D: 29,
          $W: 3,
          $H: 0,
          $m: 0,
          $s: 0,
          $ms: 0,
          $x: {},
          $isDayjsObject: true,
        },
        shiftStart: {
          $L: "en",
          $d: "2025-01-29T14:00:00.000Z",
          $y: 2025,
          $M: 0,
          $D: 29,
          $W: 3,
          $H: 8,
          $m: 0,
          $s: 0,
          $ms: 0,
          $x: {
            $localOffset: 360,
            $timezone: "America/Mexico_City",
          },
          $isDayjsObject: true,
          $offset: -360,
        },
        shiftEnd: {
          $L: "en",
          $d: "2025-01-30T02:00:00.000Z",
          $y: 2025,
          $M: 0,
          $D: 29,
          $W: 3,
          $H: 20,
          $m: 0,
          $s: 0,
          $ms: 0,
          $x: {
            $localOffset: 360,
            $timezone: "America/Mexico_City",
          },
          $isDayjsObject: true,
          $offset: -360,
        },
        attendanceStart: {
          $L: "en",
          $d: "2025-01-29T14:27:53.742Z",
          $y: 2025,
          $M: 0,
          $D: 29,
          $W: 3,
          $H: 8,
          $m: 27,
          $s: 53,
          $ms: 742,
          $x: {},
          $isDayjsObject: true,
        },
        attendanceEnd: {
          $L: "en",
          $d: "2025-01-30T02:01:36.509Z",
          $y: 2025,
          $M: 0,
          $D: 29,
          $W: 3,
          $H: 20,
          $m: 1,
          $s: 36,
          $ms: 509,
          $x: {},
          $isDayjsObject: true,
        },
        workingDayType: "Retardo",
        assignedHours: 12,
        workedHours: 11.55,
        extraHours: -0.4499999999999993,
        delayMinutes: 27,
        anticipatedMinutes: -1,
        timeOffRequestType: undefined,
        branch: "Harbor",
      },
      {
        date: {
          $L: "en",
          $d: "2025-01-30T06:00:00.000Z",
          $y: 2025,
          $M: 0,
          $D: 30,
          $W: 4,
          $H: 0,
          $m: 0,
          $s: 0,
          $ms: 0,
          $x: {},
          $isDayjsObject: true,
        },
        shiftStart: undefined,
        shiftEnd: undefined,
        attendanceStart: undefined,
        attendanceEnd: undefined,
        workingDayType: "Descanso",
        assignedHours: 0,
        workedHours: 0,
        extraHours: 0,
        delayMinutes: 0,
        anticipatedMinutes: 0,
        timeOffRequestType: undefined,
        branch: undefined,
      },
      {
        date: {
          $L: "en",
          $d: "2025-01-31T06:00:00.000Z",
          $y: 2025,
          $M: 0,
          $D: 31,
          $W: 5,
          $H: 0,
          $m: 0,
          $s: 0,
          $ms: 0,
          $x: {},
          $isDayjsObject: true,
        },
        shiftStart: undefined,
        shiftEnd: undefined,
        attendanceStart: undefined,
        attendanceEnd: undefined,
        workingDayType: "Descanso",
        assignedHours: 0,
        workedHours: 0,
        extraHours: 0,
        delayMinutes: 0,
        anticipatedMinutes: 0,
        timeOffRequestType: undefined,
        branch: undefined,
      },
      {
        date: {
          $L: "en",
          $d: "2025-02-01T06:00:00.000Z",
          $y: 2025,
          $M: 1,
          $D: 1,
          $W: 6,
          $H: 0,
          $m: 0,
          $s: 0,
          $ms: 0,
          $x: {},
          $isDayjsObject: true,
        },
        shiftStart: {
          $L: "en",
          $d: "2025-02-01T14:00:00.000Z",
          $y: 2025,
          $M: 1,
          $D: 1,
          $W: 6,
          $H: 8,
          $m: 0,
          $s: 0,
          $ms: 0,
          $x: {
            $localOffset: 360,
            $timezone: "America/Mexico_City",
          },
          $isDayjsObject: true,
          $offset: -360,
        },
        shiftEnd: {
          $L: "en",
          $d: "2025-02-02T02:00:00.000Z",
          $y: 2025,
          $M: 1,
          $D: 1,
          $W: 6,
          $H: 20,
          $m: 0,
          $s: 0,
          $ms: 0,
          $x: {
            $localOffset: 360,
            $timezone: "America/Mexico_City",
          },
          $isDayjsObject: true,
          $offset: -360,
        },
        attendanceStart: {
          $L: "en",
          $d: "2025-02-01T14:10:29.669Z",
          $y: 2025,
          $M: 1,
          $D: 1,
          $W: 6,
          $H: 8,
          $m: 10,
          $s: 29,
          $ms: 669,
          $x: {},
          $isDayjsObject: true,
        },
        attendanceEnd: {
          $L: "en",
          $d: "2025-02-02T02:07:28.834Z",
          $y: 2025,
          $M: 1,
          $D: 1,
          $W: 6,
          $H: 20,
          $m: 7,
          $s: 28,
          $ms: 834,
          $x: {},
          $isDayjsObject: true,
        },
        workingDayType: "Jornada ordinaria",
        assignedHours: 12,
        workedHours: 11.933333333333334,
        extraHours: -0.06666666666666643,
        delayMinutes: 10,
        anticipatedMinutes: -7,
        timeOffRequestType: undefined,
        branch: "Harbor",
      },
      {
        date: {
          $L: "en",
          $d: "2025-02-02T06:00:00.000Z",
          $y: 2025,
          $M: 1,
          $D: 2,
          $W: 0,
          $H: 0,
          $m: 0,
          $s: 0,
          $ms: 0,
          $x: {},
          $isDayjsObject: true,
        },
        shiftStart: undefined,
        shiftEnd: undefined,
        attendanceStart: undefined,
        attendanceEnd: undefined,
        workingDayType: "Descanso",
        assignedHours: 0,
        workedHours: 0,
        extraHours: 0,
        delayMinutes: 0,
        anticipatedMinutes: 0,
        timeOffRequestType: undefined,
        branch: undefined,
      },
    ],
    periodHours: {
      workedHours: 109.11666666666666,
      estimatedWorkedHours: 0,
      simulatedAsistanceHours: 0,
      toBeCompensatedHours: 0,
      vacationHours: 0,
      personalLeaveHours: 0,
      justifiedAbsenceByCompanyHours: 0,
      nonComputableHours: 0,
      compensationHours: 0,
      sickLeaveHours: 0,
      authorizedUnjustifiedAbsenceHours: 0,
      unjustifiedAbsenceHours: 0,
      publicHolidaysHours: 0,
      workedSundayHours: 12.366666666666667,
      expressHours: 0,
      mealDays: 9,
    },
    concludedWeeksHours: {
      restWorkedHours: 0,
      singlePlayWorkedExtraHours: 24,
      doublePlayWorkedExtraHours: 1.43333333333333,
      triplePlayWorkedExtraHours: 0,
      notWorkedHours: 0,
    },
    tardiness: 3,
    punctualityBonus: false,
  },
  salaryData: {
    maxWorkingHours: 48,
    receptionBonus: 0,
    degreeBonus: 300,
    trainingSupport: 0,
    physicalActivitySupport: 0,
    avgMonthlyOvertimeHours: 10,
    avgMonthlySundayHours: 25,
    avgMonthlyHolidayHours: 4.5,
    justifiedAbsenceCompensationPercent: 0,
    foodDayCompensation: 0,
    year: 2025,
    minimumWage: 278.8,
    uma: 113.14,
    ocupationalRisk: 0.005436,
    imssEmployerRates: {
      sicknessAndMaternity: {
        fixedFee: {
          name: "Cuota fija",
          description: "Base: UMA. 106.I",
          rate: 0.204,
        },
        surplus: {
          name: "Excedente",
          description: "Base: Diferencia entre SBC y 3 veces la UMA. 106.II",
          rate: 0.011,
        },
        cashBenefits: {
          name: "Prestaciones en dinero",
          description: "Base: SBC. 107",
          rate: 0.007,
        },
        pensionersAndBeneficiaries: {
          name: "Pensionados y beneficiarios",
          description: "Base: SBC. ???",
          rate: 0.0105,
        },
      },
      disabilityAndLife: {
        disabilityAndLife: {
          name: "Invalidez y vida",
          description: "Base: SBC. ???",
          rate: 0.0175,
        },
      },
      workRisk: {
        workRisk: {
          name: "Riesgos de trabajo",
          description: "Base: SBC. ???",
          rate: 0.005436,
        },
      },
      daycareAndSocialBenefits: {
        daycareAndSocialBenefits: {
          name: "Guarderías y prestaciones sociales",
          description: "Base: SBC. ???",
          rate: 0.01,
        },
      },
      oldAge: {
        retirement: {
          name: "Retiro",
          description: "Base: SBC. ???",
          rate: 0.02,
        },
        oldAge: [
          {
            umaLimit: 1,
            rate: 0.0315,
          },
          {
            umaLimit: 1.5,
            rate: 0.03544,
          },
          {
            umaLimit: 2,
            rate: "0.0426",
          },
          {
            umaLimit: 2.5,
            rate: "0.04954",
          },
          {
            umaLimit: 3,
            rate: "0.0537",
          },
          {
            umaLimit: 3.5,
            rate: "0.0559",
          },
          {
            umaLimit: 4,
            rate: "0.05747",
          },
          {
            umaLimit: 1000,
            rate: "0.06422",
          },
        ],
      },
      infonavit: {
        infonavit: {
          name: "Infonavit",
          description: "Base: SBC. ???",
          rate: 0.05,
        },
      },
    },
    imssEmployeeRates: {
      sicknessAndMaternity: {
        fixedFee: {
          name: "Cuota fija",
          description: "Base: UMA. 106.I",
          rate: 0,
        },
        surplus: {
          name: "Excedente",
          description: "Base: Diferencia entre SBC y 3 veces la UMA. 106.II",
          rate: 0.004,
        },
        cashBenefits: {
          name: "Prestaciones en dinero",
          description: "Base: SBC. 107",
          rate: 0.007,
        },
        pensionersAndBeneficiaries: {
          name: "Pensionados y beneficiarios",
          description: "Base: SBC. ???",
          rate: 0.0025,
        },
      },
      disabilityAndLife: {
        disabilityAndLife: {
          name: "Invalidez y vida",
          description: "Base: SBC. ???",
          rate: 0.00625,
        },
      },
      workRisk: {
        workRisk: {
          name: "Riesgos de trabajo",
          description: "Base: SBC. ???",
          rate: 0,
        },
      },
      daycareAndSocialBenefits: {
        daycareAndSocialBenefits: {
          name: "Guarderías y prestaciones sociales",
          description: "Base: SBC. ???",
          rate: 0,
        },
      },
      oldAge: {
        retirement: {
          name: "Retiro",
          description: "Base: SBC. ???",
          rate: 0,
        },
        oldAge: [
          {
            umaLimit: 1,
            rate: 0.01125,
          },
          {
            umaLimit: 1.5,
            rate: 0.01125,
          },
          {
            umaLimit: 2,
            rate: 0.01125,
          },
          {
            umaLimit: 2.5,
            rate: 0.01125,
          },
          {
            umaLimit: 3,
            rate: 0.01125,
          },
          {
            umaLimit: 3.5,
            rate: 0.01125,
          },
          {
            umaLimit: 4,
            rate: 0.01125,
          },
          {
            umaLimit: 1000,
            rate: 0.01125,
          },
        ],
      },
      infonavit: {
        infonavit: {
          name: "Infonavit",
          description: "Base: SBC. ???",
          rate: 0,
        },
      },
    },
    createdAt: "2024-10-12T11:49:00.490Z",
    createdBy: "61dff1cb4131595911ad13fb",
    updatedAt: "2025-02-02T01:23:03.821Z",
    annualIncreasePercentage: 2.5,
    employmentSubsidyAmount: 474,
    employmentSubsidyLimit: 10171,
    updatedBy: "61dff1cb4131595911ad13fb",
    minimumWageHVP: 8500,
    id: "670a622c8ff5ac02957e525a",
  },
};
